version: "3.9"
services:
  nats:
    image: nats:2.10
    command: ["-js","-m","8222","-DV"]
    ports:
      - "4222:4222"
      - "8222:8222"

  roach1:
    image: cockroachdb/cockroach:v24.1.3
    hostname: roach1
    restart: unless-stopped
    command:
      [
        "start",
        "--insecure",
        "--cluster-name=distrib",
        "--listen-addr=0.0.0.0:${COCKROACH_RPC_PORT}",
        "--sql-addr=0.0.0.0:${COCKROACH_SQL_PORT}",
        "--advertise-addr=roach1:${COCKROACH_RPC_PORT}",
        "--advertise-sql-addr=roach1:${COCKROACH_SQL_PORT}",
        "--http-addr=0.0.0.0:8080",
        "--join=roach1:${COCKROACH_RPC_PORT},roach2:${COCKROACH_RPC_PORT},roach3:${COCKROACH_RPC_PORT}"
      ]
    volumes:
      - roach1:/cockroach/cockroach-data
    ports:
      - "${COCKROACH_SQL_PORT}:${COCKROACH_SQL_PORT}"
      - "${COCKROACH_HTTP_PORT}:8080"
    healthcheck:
      test: ["CMD-SHELL", "/cockroach/cockroach sql --insecure --host=roach1:${COCKROACH_SQL_PORT} -e 'select 1' >/dev/null 2>&1"]
      interval: 5s
      timeout: 3s
      retries: 30
    depends_on:
      nats:
        condition: service_started

  roach2:
    image: cockroachdb/cockroach:v24.1.3
    hostname: roach2
    restart: unless-stopped
    command:
      [
        "start",
        "--insecure",
        "--cluster-name=distrib",
        "--listen-addr=0.0.0.0:${COCKROACH_RPC_PORT}",
        "--sql-addr=0.0.0.0:${COCKROACH_SQL_PORT}",
        "--advertise-addr=roach2:${COCKROACH_RPC_PORT}",
        "--advertise-sql-addr=roach2:${COCKROACH_SQL_PORT}",
        "--http-addr=0.0.0.0:8080",
        "--join=roach1:${COCKROACH_RPC_PORT},roach2:${COCKROACH_RPC_PORT},roach3:${COCKROACH_RPC_PORT}"
      ]
    volumes:
      - roach2:/cockroach/cockroach-data
    depends_on:
      roach1:
        condition: service_started

  roach3:
    image: cockroachdb/cockroach:v24.1.3
    hostname: roach3
    restart: unless-stopped
    command:
      [
        "start",
        "--insecure",
        "--cluster-name=distrib",
        "--listen-addr=0.0.0.0:${COCKROACH_RPC_PORT}",
        "--sql-addr=0.0.0.0:${COCKROACH_SQL_PORT}",
        "--advertise-addr=roach3:${COCKROACH_RPC_PORT}",
        "--advertise-sql-addr=roach3:${COCKROACH_SQL_PORT}",
        "--http-addr=0.0.0.0:8080",
        "--join=roach1:${COCKROACH_RPC_PORT},roach2:${COCKROACH_RPC_PORT},roach3:${COCKROACH_RPC_PORT}"
      ]
    volumes:
      - roach3:/cockroach/cockroach-data
    depends_on:
      roach2:
        condition: service_started

  db-bootstrap:
    image: cockroachdb/cockroach:v24.1.3
    depends_on:
      roach1:
        condition: service_healthy
      roach2:
        condition: service_healthy
      roach3:
        condition: service_healthy
    volumes:
      - ./db/schema.sql:/schema.sql:ro
    entrypoint: ["/bin/sh","-c"]
    command: >
      /cockroach/cockroach init --insecure --cluster-name=distrib --host=roach1:${COCKROACH_RPC_PORT} || true
      && /cockroach/cockroach sql --insecure --host=roach1:${COCKROACH_SQL_PORT} -e "create database if not exists app"
      && /cockroach/cockroach sql --insecure --host=roach1:${COCKROACH_SQL_PORT} -d app -f /schema.sql

  api:
    build: .
    command: ["/app/api"]
    environment:
      - NATS_URL=nats://nats:4222
      - HTTP_ADDR=:8080
      - STREAM_NAME=JOBS
      - STREAM_SUBJECTS=jobs.*
      - DB_DSN=postgresql://root@roach1:${COCKROACH_SQL_PORT}/app?sslmode=disable
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      db-bootstrap:
        condition: service_completed_successfully
      nats:
        condition: service_started
    ports:
      - "${API_PORT}:8080"

  worker:
    build: .
    command: ["/app/worker"]
    environment:
      - NATS_URL=nats://nats:4222
      - STREAM_NAME=JOBS
      - WORKER_TYPE=email
      - CONSUMER_NAME=worker-email
    depends_on:
      nats:
        condition: service_started

  ui:
    build:
      context: ./ui
    environment:
      - API_BASE=http://api:8080
    depends_on:
      api:
        condition: service_started
    ports:
      - "${UI_PORT}:80"

volumes:
  roach1:
  roach2:
  roach3:
